from typing import Dict
from pyro_cases.utils.base_vae import BaseVAEwRegister
from pyro_cases.utils.model import (GaussianLinearVAE,
                              GaussianLinearUniformVAE,
                              SLCPVAE,
                              SLCPwDistractorVAE,
                              BeroulliGLMRAWVAE,
                              BernoulliGLMVAE,
                              GaussianMixtureVAE,
                              TwoMoonsVAE,
                              ARM_anova_randon_nopred,
                              ARM_anova_randon_nopred_chr,
                              ARM_congress,
                              ARM_earnings1,
                              ARM_earnings2,
                              ARM_earnings_latin_square,
                              ARM_earnings_latin_square_chr,
                              ARM_earnings_vary_si,
                              ARM_earnings_vary_si_chr,
                              ARM_election88_ch14,
                              ARM_election88_ch19,
                              ARM_electric,
                              ARM_electric_1a,
                              ARM_electric_1a_chr,
                              ARM_electric_1b,
                              ARM_electric_1b_chr,
                              ARM_electric_1c,
                              ARM_electric_1c_chr,
                              ARM_electric_chr,
                              ARM_electric_inter,
                              ARM_electric_multi_preds,
                              ARM_electric_one_pred,
                              ARM_electric_supp,
                              ARM_electric_tr,
                              ARM_electric_trpre,
                              ARM_grades,
                              ARM_hiv_chr,
                              ARM_hiv_inter_chr,
                              ARM_hiv_inter,
                              ARM_hiv,
                              ARM_ideo_interactions,
                              ARM_ideo_reparam,
                              ARM_kidiq_interaction_c,
                              ARM_kidiq_interaction_c2,
                              ARM_kidiq_interaction_z,
                              ARM_kidiq_interaction,
                              ARM_kidiq_multi_preds,
                              ARM_kidscore_momhs,
                              ARM_kidscore_momiq,
                              ARM_kidscore_momwork,
                              ARM_latent_glm,
                              ARM_log10earn_height,
                              ARM_logearn_height_male,
                              ARM_logearn_height,
                              ARM_logearn_interaction_z,
                              ARM_logearn_interaction,
                              ARM_logearn_logheight,
                              ARM_mesquite_log,
                              ARM_mesquite_va,
                              ARM_mesquite_vas,
                              ARM_mesquite_vash,
                              ARM_mesquite_volume,
                              ARM_mesquite,
                              ARM_multilevel_logistic,
                              ARM_pilots_ch13,
                              ARM_pilots_ch14,
                              ARM_pilots_chr_ch13,
                              ARM_pilots_chr_ch14,
                              ARM_radon_chr,
                              ARM_radon_complete_pool,
                              ARM_radon_group_chr,
                              ARM_radon_group,
                              ARM_radon_inter_vary_chr,
                              ARM_radon_inter_vary,
                              ARM_radon_intercept_chr,
                              ARM_radon_intercept,
                              ARM_radon_no_pool_chr,
                              ARM_radon_no_pool,
                              ARM_radon_redundant_chr,
                              ARM_radon_redundant,
                              ARM_radon_vary_intercept_floor_chr,
                              ARM_radon_vary_intercept_floor,
                              ARM_radon_vary_intercept_floor2_chr,
                              ARM_radon_vary_intercept_floor2,
                              ARM_radon_vary_intercept_nofloor_chr,
                              ARM_radon_vary_intercept_nofloor,
                              ARM_radon_vary_si_chr,
                              ARM_radon_vary_si,
                              ARM_radon,
                              ARM_roaches_overdispersion,
                              ARM_separation,
                              ARM_sesame_multi_preds_3a,
                              ARM_sesame_multi_preds_3b,
                              ARM_sesame_one_pred_2b,
                              ARM_sesame_one_pred_a,
                              ARM_unemployment,
                              ARM_weight,
                              ARM_wells_d100ars,
                              ARM_wells_daae_c,
                              ARM_wells_dae_c,
                              ARM_wells_dae_inter_c,
                              ARM_wells_dae_inter,
                              ARM_wells_dae,
                              ARM_wells_dist,
                              ARM_wells_dist100,
                              ARM_wells_interaction_c,
                              ARM_wells_interaction,
                              ARM_wells_logit,
                              ARM_wells_predicted,
                              ARM_wells_probit,
                              ARM_wells,
                              ARM_y_x,
                              BUGS_beatles_probit,
                              BUGS_dyes,
                              BUGS_lsat,
                              MISC_irt_multilevel,
                              MISC_irt,
                              MISC_irt2_multilevel,
                              MISC_irt2)

vae_dict: Dict[str, BaseVAEwRegister] = {
    "gaussian_linear": GaussianLinearVAE,
    "gaussian_linear_uniform": GaussianLinearUniformVAE,
    "slcp": SLCPVAE,
    "slcp_distractors": SLCPwDistractorVAE,
    "bernoulli_glm_raw": BeroulliGLMRAWVAE,
    "bernoulli_glm": BernoulliGLMVAE,
    "gaussian_mixture": GaussianMixtureVAE,
    "two_moons": TwoMoonsVAE,
    "arm_anova_randon_nopred": ARM_anova_randon_nopred,
    "arm_anova_randon_nopred_chr": ARM_anova_randon_nopred_chr,
    "arm_congress": ARM_congress,
    "arm_earnings1": ARM_earnings1,
    "arm_earnings2": ARM_earnings2,
    "arm_earnings_latin_square": ARM_earnings_latin_square,
    "arm_earnings_latin_square_chr": ARM_earnings_latin_square_chr,
    "arm_earnings_vary_si": ARM_earnings_vary_si,
    "arm_earnings_vary_si_chr": ARM_earnings_vary_si_chr,
    "arm_election88_ch14": ARM_election88_ch14,
    "arm_election88_ch19": ARM_election88_ch19,
    "arm_electric": ARM_electric,
    "arm_electric_1a": ARM_electric_1a,
    "arm_electric_1a_chr": ARM_electric_1a_chr,
    "arm_electric_1b": ARM_electric_1b,
    "arm_electric_1b_chr": ARM_electric_1b_chr,
    "arm_electric_1c": ARM_electric_1c,
    "arm_electric_1c_chr": ARM_electric_1c_chr,
    "arm_electric_chr": ARM_electric_chr,
    "arm_electric_inter": ARM_electric_inter,
    "arm_electric_multi_preds": ARM_electric_multi_preds,
    "arm_electric_one_pred": ARM_electric_one_pred,
    "arm_electric_supp": ARM_electric_supp,
    "arm_electric_tr": ARM_electric_tr,
    "arm_electric_trpre": ARM_electric_trpre,
    "arm_grades": ARM_grades,
    "arm_hiv_chr": ARM_hiv_chr,
    "arm_hiv_inter_chr": ARM_hiv_inter_chr,
    "arm_hiv_inter": ARM_hiv_inter,
    "arm_hiv": ARM_hiv,
    "arm_ideo_interactions": ARM_ideo_interactions,
    "arm_ideo_reparam": ARM_ideo_reparam,
    "arm_kidiq_interaction_c": ARM_kidiq_interaction_c,
    "arm_kidiq_interaction_c2": ARM_kidiq_interaction_c2,
    "arm_kidiq_interaction_z": ARM_kidiq_interaction_z,
    "arm_kidiq_interaction": ARM_kidiq_interaction,
    "arm_kidiq_multi_preds": ARM_kidiq_multi_preds,
    "arm_kidscore_momhs": ARM_kidscore_momhs,
    "arm_kidscore_momiq": ARM_kidscore_momiq,
    "arm_kidscore_momwork": ARM_kidscore_momwork,
    "arm_latent_glm": ARM_latent_glm,
    "arm_log10earn_height": ARM_log10earn_height,
    "arm_logearn_height_male": ARM_logearn_height_male,
    "arm_logearn_height": ARM_logearn_height,
    "arm_logearn_interaction_z": ARM_logearn_interaction_z,
    "arm_logearn_interaction": ARM_logearn_interaction,
    "arm_logearn_logheight": ARM_logearn_logheight,
    "arm_mesquite_log": ARM_mesquite_log,
    "arm_mesquite_va": ARM_mesquite_va,
    "arm_mesquite_vas": ARM_mesquite_vas,
    "arm_mesquite_vash": ARM_mesquite_vash,
    "arm_mesquite_volume": ARM_mesquite_volume,
    "arm_mesquite": ARM_mesquite,
    "arm_multilevel_logistic": ARM_multilevel_logistic,
    "arm_pilots_ch13": ARM_pilots_ch13,
    "arm_pilots_ch14": ARM_pilots_ch14,
    "arm_pilots_chr_ch13": ARM_pilots_chr_ch13,
    "arm_pilots_chr_ch14": ARM_pilots_chr_ch14,
    "arm_radon_chr": ARM_radon_chr,
    "arm_radon_complete_pool": ARM_radon_complete_pool,
    "arm_radon_group_chr": ARM_radon_group_chr,
    "arm_radon_group": ARM_radon_group,
    "arm_radon_inter_vary_chr": ARM_radon_inter_vary_chr,
    "arm_radon_inter_vary": ARM_radon_inter_vary,
    "arm_radon_intercept_chr": ARM_radon_intercept_chr,
    "arm_radon_intercept": ARM_radon_intercept,
    "arm_radon_no_pool_chr": ARM_radon_no_pool_chr,
    "arm_radon_no_pool": ARM_radon_no_pool,
    "arm_radon_redundant_chr": ARM_radon_redundant_chr,
    "arm_radon_redundant": ARM_radon_redundant,
    "arm_radon_vary_intercept_floor_chr": ARM_radon_vary_intercept_floor_chr,
    "arm_radon_vary_intercept_floor": ARM_radon_vary_intercept_floor,
    "arm_radon_vary_intercept_floor2_chr": ARM_radon_vary_intercept_floor2_chr,
    "arm_radon_vary_intercept_floor2": ARM_radon_vary_intercept_floor2,
    "arm_radon_vary_intercept_nofloor_chr": ARM_radon_vary_intercept_nofloor_chr,
    "arm_radon_vary_intercept_nofloor": ARM_radon_vary_intercept_nofloor,
    "arm_radon_vary_si_chr": ARM_radon_vary_si_chr,
    "arm_radon_vary_si": ARM_radon_vary_si,
    "arm_radon": ARM_radon,
    "arm_roaches_overdispersion": ARM_roaches_overdispersion,
    "arm_separation": ARM_separation,
    "arm_sesame_multi_preds_3a": ARM_sesame_multi_preds_3a,
    "arm_sesame_multi_preds_3b": ARM_sesame_multi_preds_3b,
    "arm_sesame_one_pred_2b": ARM_sesame_one_pred_2b,
    "arm_sesame_one_pred_a": ARM_sesame_one_pred_a,
    "arm_unemployment": ARM_unemployment,
    "arm_weight": ARM_weight,
    "arm_wells_d100ars": ARM_wells_d100ars,
    "arm_wells_daae_c": ARM_wells_daae_c,
    "arm_wells_dae_c": ARM_wells_dae_c,
    "arm_wells_dae_inter_c": ARM_wells_dae_inter_c,
    "arm_wells_dae_inter": ARM_wells_dae_inter,
    "arm_wells_dae": ARM_wells_dae,
    "arm_wells_dist": ARM_wells_dist,
    "arm_wells_dist100": ARM_wells_dist100,
    "arm_wells_interaction_c": ARM_wells_interaction_c,
    "arm_wells_interaction": ARM_wells_interaction,
    "arm_wells_logits": ARM_wells_logit,
    "arm_wells_predicted": ARM_wells_predicted,
    "arm_wells_probit": ARM_wells_probit,
    "arm_wells": ARM_wells,
    "arm_y_x": ARM_y_x,
    "bugs_beatles_probit": BUGS_beatles_probit,
    "bugs_dyes": BUGS_dyes,
    "bugs_lsat": BUGS_lsat,
    "misc_irt_multilevel": MISC_irt_multilevel,
    "misc_irt": MISC_irt,
    "misc_irt2_multilevel": MISC_irt2_multilevel,
    "misc_irt2": MISC_irt2,
}